name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt

      - name: Update README file
        run: python today.py

      - name: Configure Git
        run: |
          git config --global user.email "110245790+Somraj-234@users.noreply.github.com"
          git config --global user.name "Somraj-234/GitHub-Actions-Bot"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Updated README" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main